task 4 complete and ready for review
jxnbox/jr-portfolio-nc-news pull request #3
Opened 2022-12-12 16:08 UTC by jxnbox

2022-12-12 16:15 UTC, popatre requested changes

2022-12-12 16:15 UTC, popatre commented on controllers.js
> +        res.status(200).send(articles);
You need to return an object, with a key of articles. 
This is the same for your controller above, but `topics`

2022-12-12 16:15 UTC, popatre commented on controllers.js
> +        console.log(articles)
remove console log

2022-12-12 16:15 UTC, popatre commented on __tests__/app.test.js
> +                    const articles = res.body;
Will need to be returned on a key of articles

2022-12-12 16:15 UTC, popatre commented on __tests__/app.test.js
> +                            })
The ticket asks for:

comment_count which is the total count of all the comments with this article_id - you should make use of queries to the database in order to achieve this.

It also doesn't want the body

2022-12-12 16:15 UTC, popatre commented on __tests__/app.test.js
> +    })
Ticket also asks for:

- [ ]  the articles should be sorted by date in descending order.

Could you add a test and the code for this?

2022-12-12 16:15 UTC, popatre commented on __tests__/app.test.js
> +        it('send a 404 status code when user inputs a bad path', () => {
nice test here

2022-12-12 16:15 UTC, popatre commented on controllers.js
>          res.status(200).send(topics);
send back an object with this key

2022-12-12 16:15 UTC, popatre commented on models.js
> +    return db.query('SELECT * FROM articles;')
Check the ticket for what it wants to be sent back, it doesnt want all the keys, and wants a comment count

2022-12-13 10:40 UTC, Pipe-Smoking-Rabbit commented on models.js
> +                if (article.article_id === comment.article_id) {
it's impressive that you've managed to achieve a comment count through javascript - but this is more easily achievable by just using SQL making use of `COUNT` and `JOIN` functionality 

I would say that you're missing an opportunity here to showcase SQL skills to employers, and so I would recommend refactoring this to just use one single SQL query that joins and creates a `comment_count` with the `COUNT` function

2022-12-13 10:43 UTC, Pipe-Smoking-Rabbit commented on controllers.js
> +        res.status(200).send(articles);
unfortunately this does still need to be changed - the response should be an object with a key containing the data, i.e. `.send({ articles: articles });`  which can be shortened to  `.send({ articles });`

2022-12-13 10:47 UTC, Pipe-Smoking-Rabbit commented on __tests__/app.test.js
> +                    expect(articles[articles.length - 1].article_id).toBe(7);
this test is great! 

We're missing some more testing though - we need to check that the data is coming back sorted by `created_at` in `desc` order as per the ticket instructions 

sounds like a job for Jest-Sorted to me

2022-12-13 10:48 UTC, Pipe-Smoking-Rabbit requested changes
There's a bit more work to be done on this ticket, it's coming along really well but just have a check over the recent comments to see what else you need to include!

2022-12-13 15:05 UTC, robert112233 approved these changes
Merge away 👍

2022-12-13 15:05 UTC, robert112233 commented on __tests__/app.test.js
> +                    expect(articles).toBeSortedBy('created_at', {descending : true});
toBeSortedBy is great to check sort order, in future you could extract this out to another test. It is good practice when using TDD to have separate tests to test individual behaviours of the function. Not a huge issue though you can still merge 👍

2022-12-13 15:11 UTC, merged